### ISSUE TITLE
Feature request: option to exclude some files

### ISSUE THREAD

**Issue by satya164** [GoogleChromeLabs/worker-plugin#12]
It'll be great if we could specify files to exclude. Currently, I get this warning `WARNING in new Worker() will only be bundled if passed a String.` because a dependency dynamically creates workers. But it's not actionable from me because I don't control this code.

**Comment by mnoandh** [comment]
no need for a dislike when the member is writing for you, (I am a beginner). thanks for your good attitude   ..... 
https://github.com/react-native-community/discussions-and-proposals/issues/41

**Comment by ilovepixelart** [comment]
Any update on this?

**Comment by developit** [comment]
Not yet, no. I want to add an `exclude` option but I'm not sure where to wire that up to [NormalModuleFactory](https://github.com/webpack/webpack/blob/master/lib/NormalModuleFactory.js#L159).

**Comment by asapzacy** [comment]
yeah this is annoying, `WARNING in new Worker() will only be bundled if passed a String.` gets logged way too often

**Comment by TheLarkInn** [comment]
@satya164 can you show me an example of how the library is using `Worker()` with dynamic code?

**Comment by satya164** [comment]
@TheLarkInn for example, you can pass worker URLs to monaco editor and it can use those URLs to create new workers.

**Comment by weekitmo** [comment]
any way to solve it now?

**Comment by blacksteed232** [comment]
hi, this is quite annoying when we use `worker-plugin` with `monaco-editor` as `monaco-editor` does dynamic loading using the construct `new Worker()` :(. Could anyone take a look at this or show us a workaround. I have tried to even filter this warning in `webpack` using `stats.warningsFilter` but seems like `worker-plugin` ignores it

**Comment by awulkan** [comment]
I'm also running into this problem with [Vue](https://github.com/vuejs/vue).
I am creating a worker in a Vue component like this:
```js
this.webWorker = new Worker('@/assets/js/workers/my-worker.js', {
    type: 'module'
});
```
And I keep getting this error:
```
new Worker() will only be bundled if passed a String.
```
The weird thing is that I have 3 web worker files, but I only get one warning.

**Comment by blacksteed232** [comment]
@developit could you take a look at this if you have some time?

**Comment by developit** [comment]
@awulkan that is a different issue than the one being discussed here. You have a Babel plugin (or something) that is transforming the `"@/assets"` path into an expression, which means it's not a String and can't be bundled.

**Comment by epascal** [comment]
I have the same issue with create-react-app, react-app-rewired
I managed to make it work and it's a delight compared to alternative plugins.
Though there is the warning three times and it's annoying

`new Worker() will only be bundled if passed a String.

new Worker() will only be bundled if passed a String.

new Worker() will only be bundled if passed a String.`

here is my configuration

config-overrides.js
`module.exports = function override(config, env) {
    const WorkerPlugin = require('worker-plugin');
    config.plugins.push(new WorkerPlugin());
    return config;
}`

In my TSX file

`const scratchWorker = new Worker('../../workers/DrawScratch/DrawScratch.worker', 
        { name:'drawscratch', type: 'module' });`

**Comment by s-h-a-d-o-w** [comment]
So far, it's only been discussed that there is a warning and people want to get rid of it. What I'm more curious about is - it's a warning, so what are the potential issues?
Personally, I don't get why `worker-plugin` tries to bundle workers of third party libraries in the first place. I would've assumed that that's already taken care of within the library...

**Comment by developit** [comment]
@s-h-a-d-o-w it's not really feasible to define what constitutes a third-party library. Things from node_modules could be relying on `new Worker('..', {type:'module'})`, and this plugin would make them function correctly. Some folks "vendor" their dependencies so they're not in a directory like `node_modules` that could be reasonably excluded by default.

At the end of the day, it's fairly confusing to apply transformations like this only to certain code. This plugin implements a web standard at build time, so it should be pretty safe to run on all code.

In terms of any ill-effects related to the warning, it's really there for the opposite reason: the warning points out failed cases where folks _do_ want WorkerPlugin to bundle a Worker, where static analysis bails out and it can't figure out the worker's entry module:

```js
import workerSrc from './somewhere-else';
new Worker(workerSrc, { type: 'module' });
```

The warning points out these cases because they're likely errors in first-party code.

That all being said, I do think the warnings are too aggressive right now. Currently, _any usage_ of `new Worker()` will trigger the warnings - that's a little much, since even non-module workers will trigger it, and they aren't even supported by the plugin. I'll open a PR to make it so that only module workers receive warnings.

**Comment by solid-droid** [comment]
I am using Angular 8.2
```
"dependencies": {
		"@angular/animations": "8.2.14",
		"@angular/cdk": "^8.2.3",
		"@angular/common": "8.2.14",
		"@angular/compiler": "8.2.14",
		"@angular/core": "8.2.14",
		"@angular/forms": "8.2.14",
````

my code: 
```javascript
if (typeof Worker !== 'undefined') {
    this.worker = new Worker( `src/app/worker/myWorker.worker` , { type: `module` });
    this.worker.onmessage = ({ data }) => {
      .....
     }
}
```  
  
**I am getting the same warning on ng serve, npm run build-dev => but its working fine**
![image](https://user-images.githubusercontent.com/32586986/130667191-2a534be3-174b-4ae2-8f3b-dbce96f68e80.png)

**but when doing npm run build-prod or prod-ci , its failing**

![image](https://user-images.githubusercontent.com/32586986/130667401-f076d407-6f51-46c3-bd93-399a553e5441.png)
