### ISSUE TITLE
Why cannot I use multiple workers for different tasks?

### ISSUE THREAD

**Issue by bfang711** [GoogleChromeLabs/worker-plugin#24]
I have two worker scripts. workerFile1.js and workerFile2.js, which do different works in the same application.  In the main script, I have 
>const worker1 = new Worker(‘workerFile1.js',{type:'module'});
>const worker2 = new Worker(‘workerFile2.js',{type:'module'});
>...
>worker1.postMessage(obj1);
...
worker2.postMessage(obj2);

But seems like this not working. both worker1 and worker2 are trying to use the latest compiled worker file logic. i.e.  If I do some modification in workerFile2.js, both of the worker1 and worker2 will do the task defined in workerFile2.js, and vice versa.  Of course, only one of the worker1 or worker2 works, and the other will throw error. 

I wonder if this is a configuration issue.  thanks.

**Comment by bfang711** [comment]
One possible solution is to combine the logic of workerFile1 and workerFile2 together by giving a type, like:
<switch (e.type){
case "logic1": { 
//logic of workerFile1 here;
break;}
case "logic2":{
//logic of workerFile2 here;
break;
}}

Although I don't want to use this method, since logic in file1 and logic in file 2 are totally different, it is a temporary solution for now. However I still want to know if there is any way to give multiple worker files.

thank you.

**Comment by developit** [comment]
This seems like a bug. Need to set up a repro.

**Comment by i0n** [comment]
I've created a really simple repo to demonstrate this bug: https://github.com/i0n/worker-plugin-bug

I'm using ngx-build-plus to provide some extra config to angular where I'm setting up worker plugin.

To reproduce:
npm install and start and then open the console for the dev server. 
We see two duplicate logs to the console from one of the worker scripts.
We should see two individual logs to the console.

You can also see this issue by looking at the network tab in dev tools, where there will be two duplicate calls to 0.worker.js (sometimes also 1.worker.js) instead of one call to 0.worker.js and one call to 1.worker.js

Sometimes if you get angular to rebuild a whole bunch of times in a row the bug will suddenly disappear. If you then restart the server the bug will reappear.

Hope this info helps, awesome project! Happy to help solve this, not super familiar with webpack internals.

**Comment by stigmergic** [comment]
I ran into this as well.  One worker was fine but adding a second worker resulted in one of my two workers being duplicated.  

As a clue for what is going on,  if I add this to `loader.js`:
`let nId = 0;` on line 26

And replace:
`const options = loaderUtils.getOptions(this) || { };
with 
`const options = loaderUtils.getOptions(this) || { name: `worker${++nId}` };`

I get both of my workers.

**Comment by filipesilva** [comment]
Now that we're also using `worker-plugin` in Angular CLI, we're seeing this bug: https://github.com/angular/angular-cli/issues/14582

**Comment by hjlld** [comment]
I have two different workers in my project, but after `npm run build`, webpack only products one 0.[project name].worker.js, the second one will replace the first one.

is it relative with worker's file name? maybe the plugin should use the name inside `new Worker( path, { name, type })` as the file name.

**Comment by developit** [comment]
@hjlld It seems like you want `output.chunkFilename` - `name` isn't contextualized at all.

I'm open to using `{ name }` from the worker constructor. Perhaps it could be used as a template value in `options.name`? Then you could do this:

```js
// webpack.config.js
new WorkerPlugin({
  filename: '[name].worker.js'
})
```

```js
// source code
new Worker('./workers/one.js', {
  name: 'one',
  type: 'module'
})
```

Another option would be to interpret the first argument to the `Worker` constructor as the output filename. I believe this would be relatively easy, I'm not sure why I used indices rather than going that route.

**Comment by filipesilva** [comment]
I'm partial to using the filename myself, because that's less onerous on users. 

In Angular CLI we do that for all lazy chunks and it works well (see [here](https://github.com/angular/angular-cli/blob/master/packages/angular_devkit/build_angular/src/angular-cli-files/plugins/named-chunks-plugin.ts)). The name itself is the full path of the request. But we also go back to having the default name based on numbers for production builds so that we don't expose source file structure.

**Comment by hjlld** [comment]
Different with Angular CLI, I'm building a JS library, I don't like providing worker files named `0.worker.js` or `1.worker.js` to my user in release distribution, it sounds wired. I prefer a good reasonable name whether name from the worker constructor's first argument or the second one.

**Comment by hjlld** [comment]
I modified `/dist/loader.js`, use following snippet to replace the original code:

```
  var options = loaderUtils.getOptions(this);
  //var chunkFilename = compilerOptions.output.chunkFilename.replace(/\.([a-z]+)$/i, '.worker.$1');
  var chunkFilename = options.name;
  var workerOptions = {
    //filename: chunkFilename.replace(/\[(?:chunkhash|contenthash)(:\d+(?::\d+)?)?\]/g, '[hash$1]'),
    filename: chunkFilename.replace(/\[(?:chunkhash|contenthash)(:\d+(?::\d+)?)?\]/g, '[hash$1]') + '.js',
    chunkFilename: chunkFilename + '.js',
    globalObject: pluginOptions.globalObject || 'self'
  };
```

now `worker-plugin` can correctly produce multiple worker files and use module name as file name.

but leads a side problem about worker path, it always require worker file from the absolute path `/` of the host.

**Comment by jamiewinder** [comment]
I've just encounted this issue myself. The best solution for now appears to be to name the workers explicitly, as in https://github.com/GoogleChromeLabs/worker-plugin/issues/24#issuecomment-506375559? 

This does leave things open to name clashes of course, as does using the first argument. All of my workers are in files called 'Worker.ts' and imported like so:
```javascript
new Worker('./Worker.ts', {...});
```
So the first argument isn't ever unique in my case.

I'm not especially clued up on Webpack or Workers, but Worker don't seem to be something you *ever* want to be bundled together because of how they work in the browser.

**Comment by developit** [comment]
@jamiewinder They should be treated as separate entries, with their own dependency trees. It seems like your Webpack configuration is set up to use static output filenames, where `worker-plugin` expects it to generate unique ones.  Can you clarify what values you have configured for `output.filename` and `output.chunkFilename`?

**Comment by developit** [comment]
@hjlld what is your webpack configuration value for `output.publicPath`?
