### ISSUE TITLE
Is it possible not to include the .worker. in the filename?

### ISSUE THREAD

**Issue by wood1986** [GoogleChromeLabs/worker-plugin#76]
https://github.com/GoogleChromeLabs/worker-plugin/blob/7dc17f0fc971bd27b3bfe99060554abd9e61276f/src/loader.js#L41

I have a naming pattern for all the chunks which is `<name>.<hash>.<ext>`. Because of  worker.js I have to do some work to handle this special and only case.

I am using inline loader `"worker-plugin/loader!./worker"`;

**Comment by developit** [comment]
This is a bit tricky, because removing the suffix can lead to name collisions. When you're injecting a hash it's extremely unlikely that collisions would occur, but the plugin can't really determine that a hash is going to be used when it generates the filename template.

That being said, I think we can definitely add support for custom name templates. I've just opened a PR that adds this:

```
new WorkerPlugin({
    filename: '[name].[hash:5].js',
    chunkFilename: '[name].[hash:5].js',
})
```

... as well as a version for loaders:

```js
import Worker from "worker-plugin/loader?filename=foo.[hash:5].js!./worker";
```
